### ISSUE TITLE
Error installing extension with gradle

### ISSUE THREAD

**Issue by fernando88to** [quarkiverse/quarkus-groovy#12]
## Expected Behavior

By following the documentation available at the link below, you should correctly install the extension in gradle.

https://github.com/quarkiverse/quarkus-groovy/blob/main/docs/modules/ROOT/pages/index.adoc

## Actual Behaviour

However, an exception is thrown when running code

`Could not get unknown property 'groovy' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

`

## Steps To Reproduce

**1- Create a new project**
`curl -L "https://code.quarkus.io/d?b=GRADLE&cn=code.quarkus.io" -o code-with-quarkus.zip`

**Add the dependency as per the documentation**

```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-arc'
    implementation "io.quarkiverse.groovy:quarkus-groovy:${quarkus-groovy.version}" // (1)
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}
```

## Version

3.0.0 

## Suggestion

1. Replace "quarkus-groovy.version" with "quarkusGroovyVersion"
2. On the pages below, the gradle installation method is the same, as it uses different variable names for the version in the gradle.properties file.

https://github.com/quarkiverse/quarkus-groovy/blob/main/docs/modules/ROOT/pages/index.adoc

https://github.com/quarkiverse/quarkus-groovy

3. Show in the documentation how to set the configuration in the 'gradle.properties' file, sometimes a beginner programmer may not know.

**Comment by essobedo** [comment]
Hi, thanks for the feedback, I look at it asap
